[package]
name = "rebound"
version = "0.1.0"
authors = ["Jonathan Daugherty <cygnus@foobox.com>"]

[dependencies]
samplers = { path = "samplers" }
nalgebra = "0.16.5"
clap = "2.32.0"
rand = "0.5.5"
rayon = "1.0.3"

[profile.dev]
opt-level = 3
